#!/bin/bash
set -v
# chmod a+x
# mplayer /usr/local/bin/ipmonitor/Sachin.mp3

curl http://192.168.0.33/relay/on
sleep 10s
xbmc-send -a "PlayMedia(/usr/local/bin/ipmonitor/Sachin.mp3)"
sleep 10s
curl http://192.168.0.33/relay/off
